### ISSUE TITLE
您好，请问能再发布一下RF200.TXT吗

### ISSUE THREAD

**Issue by Lour999** [yinzhicun/MetaF2N#4]

**Comment by yinzhicun** [comment]
Sorry for that our test dataset have something wrong for the BaiduDisk, we will upload our dataset to the Google Drive and share the link in the README soon.

**Comment by okaris** [comment]
@yinzhicun Can't access data on Baidu form overseas, is there a Google Drive alternative or could you share the RF200.txt file please?

**Comment by yinzhicun** [comment]
> @yinzhicun Can't access data on Baidu form overseas, is there a Google Drive alternative or could you share the RF200.txt file please?

Sorry for the late reply, this is the google drive link https://drive.google.com/drive/folders/13aGnJXZiEKSRanu7bu6pJGutvMvKFeuV, and the RF200.txt is in RealFaces200. This link can also be found in the updated README.md.
